# Generated by Django 2.2.4 on 2019-08-13 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, null=True)),
                ('biographie', models.TextField(null=True)),
                ('dateNaissance', models.DateTimeField(null=True)),
                ('sexe', models.CharField(max_length=2, null=True)),
                ('adresse', models.CharField(max_length=30, null=True)),
                ('ville', models.CharField(max_length=30, null=True)),
                ('poste', models.CharField(default='', max_length=100)),
                ('lieu', models.CharField(default='', max_length=30)),
                ('profilpic', models.URLField(default='connexion/images/av.png')),
                ('coverpic', models.URLField(default='connexion/images/resources/timeline-1.jpg')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_debut', models.CharField(max_length=20, null=True)),
                ('annee_debut', models.IntegerField()),
                ('mois_fin', models.CharField(max_length=20, null=True)),
                ('annee_fin', models.CharField(max_length=20, null=True)),
                ('filiere', models.CharField(max_length=50, null=True)),
                ('niveau', models.CharField(max_length=30, null=True)),
                ('lieu', models.CharField(max_length=50)),
                ('obtention', models.CharField(max_length=50, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_debut', models.CharField(max_length=20, null=True)),
                ('annee_debut', models.IntegerField()),
                ('mois_fin', models.CharField(max_length=20, null=True)),
                ('annee_fin', models.CharField(max_length=20, null=True)),
                ('filiere', models.CharField(max_length=50, null=True)),
                ('niveau', models.CharField(max_length=30, null=True)),
                ('lieu', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('niveau', models.CharField(max_length=30, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
