# Generated by Django 2.2.3 on 2019-08-10 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, null=True)),
                ('username', models.CharField(max_length=16)),
                ('profilPic', models.URLField(null=True)),
                ('coverPic', models.URLField(null=True)),
                ('biographie', models.TextField(null=True)),
                ('dateNaissance', models.DateTimeField(null=True)),
                ('sexe', models.CharField(max_length=2, null=True)),
                ('adresse', models.CharField(max_length=30, null=True)),
                ('ville', models.CharField(max_length=30, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
