# Generated by Django 2.2.4 on 2019-08-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
