# Generated by Django 2.2.4 on 2019-08-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='filiere',
            new_name='poste',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='niveau',
        ),
    ]
