# Generated by Django 2.2.4 on 2019-08-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0003_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='coverpic',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='profilpic',
            field=models.URLField(null=True),
        ),
    ]
