# Generated by Django 2.2.4 on 2019-08-14 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connexion', '0004_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubliPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legende', models.TextField(null=True)),
                ('image', models.URLField()),
                ('date_upload', models.DateTimeField(default=datetime.datetime(2019, 8, 14, 12, 7, 36, 634634))),
                ('experience', models.CharField(max_length=255, null=True)),
                ('competetence', models.CharField(max_length=255, null=True)),
                ('formmation', models.CharField(max_length=255, null=True)),
                ('personalite', models.CharField(max_length=255, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legende', models.TextField()),
                ('date_upload', models.DateTimeField(default=datetime.datetime(2019, 8, 14, 12, 7, 36, 633862))),
                ('experience', models.CharField(max_length=255, null=True)),
                ('competetence', models.CharField(max_length=255, null=True)),
                ('formmation', models.CharField(max_length=255, null=True)),
                ('personalite', models.CharField(max_length=255, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
