# Generated by Django 2.2.4 on 2019-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0004_auto_20190812_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='coverpic',
            field=models.URLField(default='connexion/images/resources/timeline-1.jpg'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profilpic',
            field=models.URLField(default='connexion/static/connexion/images/av.png'),
        ),
    ]
