# Generated by Django 2.2.4 on 2019-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0005_auto_20190812_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profilpic',
            field=models.URLField(default='connexion/images/av.png'),
        ),
    ]
