# Generated by Django 2.2.4 on 2019-08-14 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0005_publication_publiphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publiphoto',
            name='date_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
