# Generated by Django 2.2.4 on 2019-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0006_auto_20190812_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='lieu',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(default='', max_length=100),
        ),
    ]
