# Generated by Django 2.2.4 on 2019-08-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0006_auto_20190814_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date_limit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='langue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='valable',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PubliPhoto',
        ),
    ]
