# Generated by Django 2.2.4 on 2019-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0007_auto_20190814_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='personalite',
            new_name='lieu',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='date_limit',
        ),
        migrations.AddField(
            model_name='publication',
            name='date_limit_jour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_limit_mois',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='personnalite',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
