# Generated by Django 2.2.4 on 2019-08-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0008_auto_20190815_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='formmation',
            new_name='formation',
        ),
    ]
