# Generated by Django 2.2.4 on 2019-08-13 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connexion', '0009_auto_20190812_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_debut', models.CharField(max_length=20, null=True)),
                ('annee_debut', models.IntegerField()),
                ('mois_fin', models.CharField(max_length=20, null=True)),
                ('annee_fin', models.CharField(max_length=20, null=True)),
                ('filiere', models.CharField(max_length=50, null=True)),
                ('niveau', models.CharField(max_length=30, null=True)),
                ('lieu', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
