# Generated by Django 2.2.4 on 2019-08-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0011_auto_20190815_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date_upload',
        ),
    ]
