# Generated by Django 2.2.4 on 2019-08-15 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0012_remove_publication_date_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='valable',
        ),
        migrations.AddField(
            model_name='publication',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 11, 4, 6, 455528, tzinfo=utc)),
        ),
    ]
