# Generated by Django 2.2.4 on 2019-08-15 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0013_auto_20190815_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='valable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_upload',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 15, 11, 7, 0, 211898, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='legende',
            field=models.TextField(null=True),
        ),
    ]
